---
system:
    verbose: 0
    narrow_output: false
    parallel_requests: 1
    parallel_attempts: 1
    lite: true
    show_z: false

run:
    seed:
    deprefix: true
    eval_threshold: 0.5
    generations: 5
    probe_tags:

plugins:
    model_type: nim
    model_name: nvidia/nemotron-mini-4b-instruct
    probe_spec: all
    detector_spec: auto
    extended_detectors: false
    buff_spec:
    buffs_include_original_prompt: false
    buff_max:
    detectors:
      PythonPypi:
        config:
            cutoff_date: "2023-12-01 00:00:00 +0000"
      JavaScriptNpm:
        config:
            cutoff_date: "2023-12-01 00:00:00 +0000"
      RubyGems:
        config:
            cutoff_date: "2023-12-01 00:00:00 +0000"
    generators: {}
    buffs: {}
    harnesses: {}
    probe_spec: packagehallucination.Python
    probes:
        encoding:
            payloads:
                - default

reporting:
    report_prefix:
    taxonomy:
    report_dir: garak_runs
    show_100_pass_modules: true