name: "Garak linting"

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      python-version: 3.10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ strategy.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Test with pytest
        run: |
          pylint garak